version: 2

jobs:
  build:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run:
          name: Pull submodules
          command: git submodule init && git submodule update --remote
      - run:
          name: Compile
          command: make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
